import hashlib,json,pathlib
root=pathlib.Path('/work');home='/home/someguy/codebase/0xJesus/ComandOS/.worktrees/rust-migration/'
p=root/'.superpowers/sdd/schema-traversal-frozen.json';frozen=json.loads(p.read_text())
owned=['crates/comandos-extensions/src/output_schema.rs','crates/comandos-extensions/src/output_schema/dialect.rs','crates/comandos-extensions/src/output_schema/traversal.rs','crates/comandos-extensions/src/output_schema/traversal/local_refs.rs','crates/comandos-extensions/src/output_schema/traversal/PROVENANCE.json','crates/comandos-extensions/src/output_schema/traversal/JSONSCHEMA-COPYING','crates/comandos-extensions/src/output_schema/traversal/REFERENCING-COPYING','crates/comandos-extensions/tests/output_schema_traversal_audit.py','crates/comandos-extensions/tests/output_schema_traversal_cases.json']
frozen['final_files']=[{'path':home+name,'sha256':hashlib.sha256((root/name).read_bytes()).hexdigest()} for name in owned]
frozen['source_register_additional']=[]
source_rows=[('/venv/lib/python3.11/site-packages/mcp/client/session.py','/home/someguy/.local/share/comandos/extensions-venv/lib/python3.11/site-packages/mcp/client/session.py'),('/usr/lib/python3.11/urllib/parse.py','/usr/lib/python3.11/urllib/parse.py'),('/work/lib/extension_proxy.py',home+'lib/extension_proxy.py')]
for native in ['options.rs','validator.rs','keywords/required.rs']:
    suffix='.migration-build/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/jsonschema-0.58.4/src/'+native;source_rows.append(('/work/'+suffix,home+suffix))
for path,original in source_rows:frozen['source_register_additional'].append({'path':original,'sha256':hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()})
frozen['artifacts']=[{'path':home+str(path.relative_to(root)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()} for path in [root/'.migration-build/target/release/comandos-extensions',pathlib.Path((root/'.superpowers/sdd/schema-traversal-library-binary.txt').read_text().strip())]]
frozen['execution']={'date':'2026-10-03','root_versions':{'jsonschema':'4.26.0','referencing':'0.37.0','mcp':'1.30.0','jsonschema-specifications':'2025.9.1','native-jsonschema':'0.58.4'},'worker_budget':{'address_space_bytes':384*1024*1024,'cpu_seconds':[2,3]},'test_probe':{'batch_rows':8,'max_input_bytes':8*1024*1024,'max_name_bytes':512,'max_reported_pointer_characters':4096},'evaluator_limits':{'active_frames':128,'operations':100000,'crawl_depth':512,'crawl_resources':100000},'productive_depth_observations':{'native_valid':63,'native_evaluation_gap':64,'native_parser_gap':160,'python_valid_at':[1,8,24,48,63,64,96,160]},'sequencing_exception':'A cached Cargo no-run artifact discovery overlapped ordinary pytest; no compilation occurred and no interference was observed.'}
frozen['evidence']=[{'path':home+str(path.relative_to(root)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()} for path in sorted((root/'.superpowers/sdd').glob('schema-traversal-*.json')) if path!=p]
frozen['report']={'path':home+'.superpowers/sdd/schema-traversal-report.md','sha256':hashlib.sha256((root/'.superpowers/sdd/schema-traversal-report.md').read_bytes()).hexdigest()}
frozen['verification_logs']=[{'path':home+str(path.relative_to(root)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()} for path in sorted((root/'.superpowers/sdd').glob('schema-traversal-*.log'))]
p.write_text(json.dumps(frozen,indent=2)+'\n')
(root/'.superpowers/sdd/schema-traversal-writing-notes.txt').write_text('Kind: descriptive dependency audit | Audience: controller and independent Rust reviewer | Purpose: assess the exact private traversal boundary and retained gaps | Non-goals: production wiring, full MCP diagnostic parity, numeric/regex engines, general resources, all-input resource parity\n')
print('Frozen',len(frozen['final_files']),'owned files;',len(frozen['source_register_additional']),'additional source hashes;',len(frozen['evidence']),'evidence hashes')
