import json,pathlib,sys
web=pathlib.Path(sys.argv[1]).resolve()
m=json.loads((web/'manifest.json').read_text())['files']
css=next(v for k,v in m.items() if k.endswith('-workspace.css'))
fixture='''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="comandos-web" content="command-sidebar"><link rel="stylesheet" href="/CSS"><style>:root{--bg:#0c1220;--panel:#101928;--panel2:#172238;--line:#2b3c54;--line2:#2b3c54;--text:#dce8ef;--dim:#879bad;--brand:#73d6e8;--mono:monospace;--sans:system-ui}body{margin:0;background:var(--bg);color:var(--text)}#command-sidebar{position:relative;display:flex;flex-direction:column;width:360px;height:100dvh;border-right:1px solid var(--line)}button{font:inherit;cursor:pointer} @media(max-width:500px){#command-sidebar{width:100vw}}</style></head><body><span id="clock">18:30</span><aside id="command-sidebar"></aside><script type="module">
import init,{boot} from '/WASMJS';await init({module_or_path:new URL('/WASMBIN',location.href)});boot('');
window.target={session:'one',pane:'%1'};window.calls=[];window.deferred=[];window.hold=false;window.limitCalls=0;window.errors=[];window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));window.inApp=()=>false;
const entry=(name,directory=false,root='/project/one')=>({name,directory,path:root+'/'+name,relative:name,symlink:false});
window.api=async(path,body)=>{calls.push({path,body});if(path.startsWith('/commands/catalog'))return {catalog:{clis:[]}};if(path==='/chains')return {chains:[]};if(path==='/open-path')return {ok:true};if(path==='/credits/openrouter')return {connected:true,total_credits:50,total_usage:12.5,remaining:37.5};if(path==='/fs/explorer'){const root='/project/'+body.session;let entries=body.path?[entry('nested.rs',false,root)]:[entry('src',true,root),entry('loop',true,root),entry('main.rs',false,root),entry('<unsafe>.txt',false,root),...Array.from({length:20},(_,i)=>entry('dir'+i,true,root))];if(body.path==='loop')entries=[entry('loop',true,root)];const v={root,path:body.path==='loop'?'':body.path,pane:body.pane,entries,truncated:false};if(hold)return new Promise(resolve=>deferred.push(()=>resolve(v)));return v;}throw Error(path)};
window.sb=ComandosCommandSidebar.createCommandSidebar({root:document.querySelector('#command-sidebar'),api,getTarget:()=>target,storage:localStorage,terminals:()=>[],renderLimits:slot=>{limitCalls++;slot.textContent='Claude · 42%';},toast:m=>{window.lastToast=m;}});await sb.refresh();window.ready=true;
</script></body></html>'''.replace('CSS',css).replace('WASMJS',m['comandos_web.js']).replace('WASMBIN',m['comandos_web_bg.wasm'])
(web/'sidebar-fixture.html').write_text(fixture)
print(web/'sidebar-fixture.html')
