// Actual Rust/WASM versus the unchanged source tail, using a deterministic DOM.
// node ABS_TEST_PATH ABS_WASM_BINDGEN_NODE_MODULE
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {doc,makeEl}=require('./dom_stub.cjs');
const native=require(process.argv[2]);
Object.defineProperty(Object.prototype,'append',{configurable:true,value(child){return this.appendChild(child)}});
Object.defineProperty(Object.prototype,'getBoundingClientRect',{configurable:true,value(){return {left:0,top:0,width:400,height:400,bottom:24}}});
const source=fs.readFileSync(require('node:path').join(__dirname,'../dash/term.html'),'utf8').split('/* Marcos + cabecera B por pane en el remoto')[1].split('</script>')[0];
const tick=async()=>{for(let i=0;i<14;i++)await new Promise(r=>setImmediate(r));};
const brand=(name,test)=>global[name]=class{static[Symbol.hasInstance](x){return test(x)}};
brand('Window',x=>x===global.window);brand('Element',x=>x?.nodeType===1);brand('EventTarget',x=>typeof x?.addEventListener==='function');brand('MouseEvent',x=>x?.clientX!==undefined);brand('Event',x=>!!x?.type);brand('Document',x=>x===doc);
async function run(wasm){
 const listeners={},timers=new Map(),intervals=new Map();let id=0,clock=1000;let dataCb,resizeCb;
 const win={document:doc,location:{search:'?arg=demo&auth=token',href:'http://fixture/term/?arg=demo&auth=token'},parent:{openTerms:new Map([['demo',{label:'Label<&'}]]),openPaneExtensions(...args){requests.push(['extension',args]);}},addEventListener(t,f){(listeners[t]??=[]).push(f)},removeEventListener(t,f){listeners[t]=(listeners[t]??[]).filter(x=>x!==f)},setTimeout(f,ms){timers.set(++id,{f,ms});return id},clearTimeout(i){timers.delete(i)},setInterval(f,ms){intervals.set(++id,{f,ms});return id},clearInterval(i){intervals.delete(i)}};
 const orig=doc.createElement;doc.createElement=tag=>{const e=orig(tag);const rawQuery=e.querySelectorAll;e.querySelectorAll=selector=>selector.split(',').flatMap(sel=>sel.trim().endsWith(':not(:disabled)')?rawQuery(sel.trim().slice(0,-15)).filter(x=>!x.disabled&&!x.hasAttribute('disabled')):rawQuery(sel.trim()));e.querySelector=sel=>e.querySelectorAll(sel)[0]||null;const d=Object.getOwnPropertyDescriptor(e,'innerHTML');let raw='';Object.defineProperty(e,'innerHTML',{configurable:true,get:()=>raw,set:v=>{raw=v;d.set.call(e,v)}});e.replaceChildren=(...xs)=>{e.children=[];xs.forEach(x=>e.appendChild(x))};e.append=e.appendChild;e.getBoundingClientRect=()=>({left:0,top:0,width:400,height:400,bottom:24});e.insertAdjacentHTML=(p,html)=>{const wrapper=orig('div');wrapper.innerHTML=html;for(const c of [...wrapper.children])e.appendChild(c)};return e;};
 doc.body=doc.createElement('body');doc.hidden=false;doc.readyState='complete';doc.getElementById=id=>doc.body.querySelector('#'+id);doc.querySelector=s=>doc.body.querySelector(s);const termEl=doc.createElement('div');termEl.setAttribute('id','term');const screen=doc.createElement('div');screen.className='xterm-screen';screen.clientWidth=328;screen.clientHeight=352;termEl.appendChild(screen);const layer=doc.createElement('div');layer.setAttribute('id','pane-chrome');doc.body.appendChild(termEl);doc.body.appendChild(layer);
 const panes=[{id:'%1',left:0,top:1,width:20,height:21,active:true},{id:'%2',left:21,top:1,width:20,height:21,active:false}];let models=[{pane:'%1',motor:'claude',harness:'claude',model:'m<&',state:'verified',effort:'high',hAcct:'work'},{pane:'%2',motor:'codex',harness:'codex',state:'changing',target:'next',hAcct:'unknown'}];const requests=[];let switchState='confirmed',holdList=false,resumeList;
 const term={cols:41,rows:22,screen,cellWidth:8,cellHeight:16,_core:{_renderService:{dimensions:{css:{cell:{width:8,height:16}}}}},onData(cb){dataCb=cb;return{dispose(){dataCb=null}}},onResize(cb){resizeCb=cb;return{dispose(){resizeCb=null}}}};win.__comandosTerm=term;
 win.fetch=async(path,opts={})=>{assert.equal(opts.headers['X-Comandos-Token'],'token');if(path.startsWith('/tab-models'))assert.equal(opts.headers['Content-Type'],'application/json');const body=opts.body&&JSON.parse(opts.body);requests.push([path,body??null]);let data={};if(path==='/terminal-panes')data={panes,remoteFocus:'%1'};else if(path.startsWith('/tab-models'))data={panes:models};else if(path.startsWith('/accounts'))data={accounts:[{alias:'work',identity:'me<&',selectable:true,limits:[{label:'weekly',percent:95}]},{alias:'other',identity:'you',selectable:true,limits:[]},{alias:'login',identity:'',selectable:false,limits:[]}]};else if(path==='/account/add')data={ok:true,session:'login-tab',alias:'new'};else if(path==='/account/switch')data={ok:true,operationKey:'k',operationId:'id'};else if(path.startsWith('/model/status'))data={ok:true,state:switchState};if(path==='/terminal-panes'&&body?.action==='list'&&holdList){holdList=false;return{ok:true,json:()=>new Promise(r=>resumeList=()=>r(data))}}return{ok:true,json:async()=>data}};
 global.window=win;global.document=doc;global.location=win.location;global.parent=win.parent;global.fetch=win.fetch;global.URLSearchParams=URLSearchParams;global.ResizeObserver=undefined;Date.now=()=>clock;
 if(wasm)native.attach_pane_chrome();else vm.runInNewContext('/* Marcos + cabecera B por pane en el remoto'+source,{window:win,document:doc,location:win.location,parent:win.parent,fetch:win.fetch,URLSearchParams,URL,Date,setInterval:win.setInterval,clearInterval:win.clearInterval,setTimeout:win.setTimeout,clearTimeout:win.clearTimeout});
 await tick();const snapshots=[];const frames=()=>layer.children[0];snapshots.push(frames().innerHTML);assert.ok(frames().innerHTML.includes('Label&lt;&amp;'));assert.ok(frames().innerHTML.includes('m&lt;&amp;'));assert.equal(requests.length,2);
 const event=(extra={})=>({button:0,detail:1,clientX:164,clientY:100,preventDefault(){},stopPropagation(){},...extra});holdList=true;clock=4000;[...intervals.values()].find(x=>x.ms===2000).f();await tick();clock=4100;termEl.dispatch('mousedown',termEl,event({clientX:200}));assert.ok(frames().innerHTML.includes('pc-frame on\" style=\"left:166px'));resumeList();await tick();snapshots.push(frames().innerHTML);assert.ok(frames().innerHTML.includes('pc-frame on\" style=\"left:166px'));clock=4200;[...intervals.values()].find(x=>x.ms===2000).f();await tick();snapshots.push(frames().innerHTML);
 termEl.dispatch('mousemove',termEl,event());snapshots.push(layer.children[1].innerHTML);termEl.dispatch('mousedown',termEl,event({detail:2}));await tick();assert.equal(requests.at(-1)[1]?.action,'resize');assert.equal(requests.at(-1)[1]?.size,20);
 termEl.dispatch('mousedown',termEl,event());for(const f of listeners.mousemove??[])f({type:'mousemove',...event({clientX:180})});for(const f of listeners.mousemove??[])f({type:'mousemove',...event({clientX:188})});await tick();assert.equal(requests.at(-1)[1].size,23);for(const f of listeners.mouseup??[])f({type:'mouseup',...event()});assert.ok([...timers.values()].some(x=>x.ms===60));
 const account=frames().querySelector('button[data-act="acct"]');layer.dispatch('click',account);await tick();const box=layer.children[2].children[0];snapshots.push(box.innerHTML);assert.ok(box.innerHTML.includes('full'));assert.ok(box.innerHTML.includes('me&lt;&amp;'));
 const add=box.querySelector('[data-add-account]');if(add.onclick)add.onclick();else box.dispatch('click',add);await tick();assert.equal(requests.at(-1)[0],'/account/add');assert.deepEqual(requests.at(-1)[1],{provider:'claude',alias:'',deviceAuth:true});assert.ok((box.querySelector('a').href||box.querySelector('a').getAttribute('href')).includes('arg=login-tab'));
 doc.dispatch('keydown',{key:'Escape'});assert.equal(layer.children[2].children.length,0);layer.dispatch('click',account);await tick();const b2=layer.children[2].children[0],other=b2.querySelector('[data-alias="other"]');if(wasm)b2.dispatch('click',other);else other.dispatch('click',other);await tick();assert.equal(requests.at(-1)[0],'/account/switch');const pending=[...timers.values()].find(x=>x.ms===1500);assert.ok(pending);pending.f();await tick();assert.ok(requests.some(x=>x[0]==='/model/status?operationKey=k&operationId=id'));assert.ok(b2.textContent.includes('Listo: este pane'));
 const ext=frames().querySelector('button[data-act="ext"]');layer.dispatch('click',ext);assert.deepEqual(requests.at(-1),['extension',['demo','%1','claude']]);dataCb('\x02');clock+=100;dataCb('o');assert.ok([...timers.values()].some(x=>x.ms===80));resizeCb({cols:41,rows:22});assert.ok([...timers.values()].some(x=>x.ms===60));doc.hidden=true;const before=requests.length;[...intervals.values()].find(x=>x.ms===2000).f();await tick();assert.equal(requests.length,before);
 if(wasm){native.release_pane_chrome();assert.equal(termEl.listenerCount('mousedown'),0);assert.equal(dataCb,null);assert.equal(resizeCb,null);assert.equal(intervals.size,0);}else{for(const k of ['keydown','mousedown','visibilitychange']){/* fresh document listeners are cleared below */}}
 // The shared stub exposes remove but no clear; every legacy listener is removed
 // by using a fresh module document on each process (oracle runs in child below).
 return{snapshots,requests};
}
if(process.argv[3]==='legacy'){run(false).then(x=>process.stdout.write(JSON.stringify(x))).catch(e=>{console.error(e);process.exitCode=1});}else{const {spawnSync}=require('node:child_process');const oracle=spawnSync(process.execPath,[__filename,process.argv[2],'legacy'],{encoding:'utf8'});assert.equal(oracle.status,0,oracle.stderr);run(true).then(x=>{assert.deepEqual(x,JSON.parse(oracle.stdout));console.log('term-tail actual WASM/source contracts: frames/gutters/resize/accounts/login/switch/poll/focus/cleanup passed');}).catch(e=>{console.error(e);process.exitCode=1});}
