// Original terminal UI and actual WASM use the same private transport and DOM.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {doc,makeEl,parse}=require('../../comandos-web/tests/full_native_boot_dom.cjs');
const native=process.argv[2]!=='--record',snapshot=[],calls=[],sends=[],timers=[],frames=[],outputs=[],resizes=[],events={};let ackResolve,handler,borders=false,nativeSelection=null;const devices=process.argv.includes('--devices');
const root=makeEl('html',{},null);doc.documentElement=root;doc.body=makeEl('body',{},root);root.appendChild(doc.body);parse(fs.readFileSync(path.resolve(__dirname,'../../comandos-web-view/src/term_page_body.html'),'utf8'),doc.body);
doc.getElementById=id=>root.querySelector('#'+id);doc.querySelector=s=>root.querySelector(s);doc.querySelectorAll=s=>root.querySelectorAll(s);doc.readyState='complete';
for(const n of root.querySelectorAll('*')){n.blur=()=>{if(doc.activeElement===n)doc.activeElement=null};n.setSelectionRange=(a,b)=>{n.selectionStart=a;n.selectionEnd=b};n.selectionStart=n.selectionEnd=0;n.setRangeText=(v,a,b)=>{n.value=n.value.slice(0,a)+v+n.value.slice(b);n.setSelectionRange(a+v.length,a+v.length)};n.append=(...xs)=>xs.forEach(x=>n.appendChild(x));n.showModal=()=>{n.open=true};n.close=()=>{n.open=false;n.dispatch('close')};}
const oldCreate=doc.createElement;doc.createElement=tag=>{const n=oldCreate(tag);n.append=(...xs)=>xs.forEach(x=>n.appendChild(x));return n};
const storage=new Map(),clipboard=[];if(devices)storage.set("comandos.deviceId","private-device");Object.defineProperty(global,'navigator',{configurable:true,writable:true,value:{maxTouchPoints:1,clipboard:{writeText:async s=>clipboard.push(s),readText:async()=> 'clip'}}});
Object.assign(global,{window:global,parent:global,document:doc,location:{search:'?arg=private-session&auth=private-token&theme=dia&btn=pixel',protocol:'https:',host:'private.invalid',hostname:'private.invalid',origin:'https://private.invalid',pathname:'/term/',href:'https://private.invalid/term/'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},addEventListener:(t,f)=>(events[t]||=[]).push(f),removeEventListener(){},postMessage(){},getSelection:()=>nativeSelection,getComputedStyle:()=>({lineHeight:'22px'}),setTimeout:(f,ms)=>{timers.push([f,ms]);return timers.length},clearTimeout(){},setInterval:(f,ms)=>{timers.push([f,ms]);return timers.length},clearInterval(){},requestAnimationFrame:f=>{frames.push(f);return frames.length},cancelAnimationFrame(){},ResizeObserver:class{observe(){}disconnect(){}},Element:class{static[Symbol.hasInstance](v){return v?.nodeType===1}},Window:class{static[Symbol.hasInstance](v){return v===global}},EventTarget:class{static[Symbol.hasInstance](v){return typeof v?.addEventListener==='function'}}});
const ta=makeEl('textarea',{},null),screen=makeEl('div',{class:'xterm-screen'},null);doc.getElementById('term').appendChild(screen);screen.appendChild(ta);ta.focus=()=>doc.activeElement=ta;ta.blur=()=>doc.activeElement=null;
const options={fontFamily:'monospace',fontSize:14,lineHeight:1.2,letterSpacing:0};const transport={options,cols:80,rows:24,cellWidth:8,cellHeight:16,screen,textarea:ta,modes:{bracketedPasteMode:true,mouseTrackingMode:'none'},buffer:{active:{length:24,viewportY:0,getLine:()=>({isWrapped:false,translateToString:()=> 'local output',getCell:c=>({getChars:()=>borders&&c===8?'│':''})})}},loadAddon(){},open(){},registerLinkProvider(){},onData(f){this.data=f},onResize:f=>resizes.push(f),onSelectionChange(){},onWriteParsed:f=>outputs.push(f),attachCustomKeyEventHandler(){},focus:()=>ta.focus(),blur:()=>ta.blur(),getSelection:()=>'',hasSelection:()=>false,refresh(){},write(){},reset(){},paste:s=>sends.push(['paste',s]),sendInput:(s,q)=>{sends.push(['input',s,!!q]);return true},sendWithAck:s=>{sends.push(['ack',s]);return new Promise(r=>ackResolve=r)},setCtrlArmed:on=>{transport.ctrl=on},isOpen:()=>true,scheduleFit(){},cellChar:(c,r)=>borders&&c===9?'│':'',localHistory:()=> 'local output'};
let sockets=[];class Socket{constructor(){this.readyState=1;this.listeners={};sockets.push(this)}addEventListener(t,f){(this.listeners[t]||=[]).push(f)}send(d){(this.sent||=[]).push(typeof d==='string'?d:Array.from(d));if(typeof d==='string')return;sends.push(['wire',Array.from(d)]);}close(){}fire(t,data){for(const f of this.listeners[t]||[])f({data});}}
Object.assign(global,{Terminal:class{constructor(opts){transport.options={...opts};return transport}},FitAddon:{FitAddon:class{fit(){}proposeDimensions(){return{cols:80,rows:24}}}},CanvasAddon:{CanvasAddon:class{}},WebLinksAddon:{WebLinksAddon:class{}},LigaturesWebAddon:class{},WebSocket:Socket});
let panes=[{id:'%1',identity:'one',title:'bash',path:'/private/project',active:true},{id:'%2',identity:'two',title:'codex',path:'/private/other'}];handler=async(p,b)=>p==='/terminal-history'?{ok:true,text:'first\nsecond\nthird',pane:'%1',panes}:p==='/terminal-panes'?{ok:true,panes,clientKeys:b.action==='select'?'\x1b[Z':undefined}:p.startsWith('/workspace/client')?{drafts:{'tab:private-session':{text:'saved device draft',selStart:2,selEnd:7}},anchors:{'tab:private-session':{text:'second',ratio:0.4}}}:{};
global.fetch=async(p,o={})=>{const b=o.body?JSON.parse(o.body):null;calls.push([p,b]);const payload=await handler(p,b);return{ok:true,status:200,json:async()=>payload}};
if(global.__terminalPageFixtureOnly){module.exports={doc,makeEl,root,transport,sockets,calls,timers,frames,events};return;}
let ui;if(devices&&!native)vm.runInThisContext(fs.readFileSync(path.resolve(__dirname,'../../../dash/device-drafts.js'),'utf8'));if(native){const wasm=require(path.resolve(process.argv[2]));assert.equal(typeof wasm.TerminalControls,'function','native terminal UI constructor missing');ui=new wasm.TerminalControls(transport);}else{const source=fs.readFileSync(path.resolve(__dirname,'../../../dash/term.html'),'utf8');const start=source.indexOf('(function () {',source.indexOf('<script>',source.indexOf('id="pane-dialog"')));const end=source.indexOf('</script>',start);vm.runInThisContext(source.slice(start,end),{filename:'original-terminal-main'});}
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r))};const id=k=>doc.getElementById(k),action=k=>doc.querySelector('[data-action="'+k+'"]');function click(node){node.dispatch('click',node);id('term-toolbar').dispatch('click',node)}function save(name,data){snapshot.push({name,data})}
(async()=>{await settle();if(devices)save('device-restore',{text:id('mobile-draft').value,range:[id('mobile-draft').selectionStart,id('mobile-draft').selectionEnd]});save('mobile-start',{compose:id('mobile-compose').hidden,readonly:ta.readOnly,keyboard:action('keyboard').textContent});
 id('mobile-draft').value='draft\ntext\x1b';id('mobile-draft').dispatch('input');id('mobile-compose').dispatch('submit');await settle();save('draft-framing',native?sends.findLast(x=>x[0]==='ack')[1]:new TextDecoder().decode(Uint8Array.from(sends.findLast(x=>x[0]==='wire')[1].slice(1))));save('draft-pending',{text:id('mobile-draft').value,stored:storage.get('comandos:terminal-draft:private-session')});if(native)ackResolve(true);else sockets[0].fire('message',new TextEncoder().encode('0response').buffer);await settle();save('draft-ack',{text:id('mobile-draft').value,stored:storage.get('comandos:terminal-draft:private-session')||null});
 click(action('history'));await settle();save('history-open',{hidden:id('terminal-history').hidden,text:id('history-text').value,status:id('history-status').textContent,range:[id('history-text').selectionStart,id('history-text').selectionEnd],toolbar:id('term-toolbar').hidden});id('history-text').setSelectionRange(1,1);id('history-text').dispatch('click');save('tap-select',{range:[id('history-text').selectionStart,id('history-text').selectionEnd],status:id('history-status').textContent});id('selection-copy').click();await settle();save('copy',clipboard.slice());id('history-text').setSelectionRange(0,5);id('history-text').scrollTop=0;id('history-text').clientHeight=22;id('selection-toolbar').dispatch('click',doc.querySelector('[data-selection-line="down"]'));save('extend-and-scroll',{range:[id('history-text').selectionStart,id('history-text').selectionEnd],scrollTop:id('history-text').scrollTop});outputs.forEach(f=>f());save('history-output',id('history-status').textContent);id('selection-close').click();save('history-close',{hidden:id('terminal-history').hidden,compose:id('mobile-compose').hidden});nativeSelection={anchorNode:id('history-text'),toString:()=> 'native selection',removeAllRanges:()=>nativeSelection=null};click(action('copy'));await settle();save('native-selection-copy',clipboard.slice());
 click(action('panes'));await settle();save('pane-list',{open:id('pane-dialog').open,labels:id('pane-list').querySelectorAll('strong').map(n=>n.textContent),status:id('pane-status').textContent});const close=id('pane-list').querySelector('.danger');close.click();save('close-confirm',{hidden:id('pane-confirm').hidden,label:id('pane-confirm-label').textContent,requests:calls.filter(([p,b])=>p==='/terminal-panes'&&b.action==='close').length});id('pane-cancel').click();save('close-cancel',{hidden:id('pane-confirm').hidden,list:id('pane-list').hidden});id('pane-list').querySelector('.danger').click();id('pane-close-confirm').click();await settle();save('close-request',calls.filter(([p,b])=>p==='/terminal-panes'&&b.action==='close').map(([,b])=>b));
 doc.dispatch('wheel',{target:screen,deltaY:56,clientX:110,clientY:160});for(let i=0;i<20&&frames.length;i++)frames.shift()();await settle();save('mouse-off-wheel',calls.filter(([p])=>p==='/tmux-scroll').map(([,b])=>b));const touch={identifier:4,clientX:110,clientY:160,screenX:110,screenY:160};doc.dispatch('touchstart',{target:screen,touches:[touch]});const hold=timers.findLast(([,ms])=>ms===520);assert(hold,'history long press timer');hold[0]();await settle();save('longpress-history',{hidden:id('terminal-history').hidden,request:calls.filter(([p])=>p==='/terminal-history').at(-1)[1]});
 id('selection-close').click();id('mobile-draft').value='unconfirmed';id('mobile-draft').dispatch('input');id('mobile-compose').dispatch('submit');await settle();if(native)ackResolve(false);else timers.findLast(([,ms])=>ms===4000)[0]();await settle();save('ack-failure-retains',{text:id('mobile-draft').value,error:id('err').textContent});id('mobile-draft').value='old';id('mobile-draft').dispatch('input');id('mobile-compose').dispatch('submit');await settle();id('mobile-draft').value='new edit';id('mobile-draft').dispatch('input');if(native)ackResolve(true);else sockets[0].fire('message',new TextEncoder().encode('0response').buffer);await settle();save('ack-preserves-new-edit',id('mobile-draft').value);id('mobile-draft').dispatch('compositionstart');id('mobile-compose').dispatch('submit');await settle();save('composition-no-send',id('mobile-draft').value);id('mobile-draft').dispatch('compositionend');let releaseHistory;handler=async(p,b)=>p==='/terminal-history'?new Promise(r=>releaseHistory=r):{};click(action('history'));await settle();id('selection-close').click();releaseHistory({ok:true,text:'stale should not render',panes:[]});await settle();save('stale-history',{hidden:id('terminal-history').hidden,text:id('history-text').value,status:id('history-status').textContent});handler=async(p,b)=>p==='/terminal-history'?{ok:true,text:'😀x\nβ\nlast',panes:[]}:{};click(action('history'));await settle();id('history-text').setSelectionRange(1,1);id('history-text').dispatch('click');save('unicode-selection',{range:[id('history-text').selectionStart,id('history-text').selectionEnd],status:id('history-status').textContent});
id('selection-close').click();borders=true;transport.modes.mouseTrackingMode='any';const beforeResize=sends.length;doc.dispatch('touchstart',{target:screen,touches:[touch]});timers.findLast(([,ms])=>ms===220)[0]();doc.dispatch('touchmove',{target:screen,touches:[{...touch,clientX:180}]});for(let i=0;i<20&&frames.length;i++)frames.shift()();doc.dispatch('touchend',{target:screen,changedTouches:[{...touch,clientX:180}]});const resized=sends.slice(beforeResize).filter(x=>['wire','input'].includes(x[0])).map(x=>x[0]==='wire'?new TextDecoder().decode(Uint8Array.from(x[1].slice(1))):x[1]);save('snap-resize-press-motion-release',resized);
 const golden=path.join(__dirname,devices?'terminal_controls_devices_golden.json':'terminal_controls_golden.json');if(native){assert.deepEqual(snapshot,JSON.parse(fs.readFileSync(golden)));ui.dispose();console.log('Terminal controls actual WASM equals original',snapshot.length,'checkpoints')}else{fs.writeFileSync(golden,JSON.stringify(snapshot,null,2)+'\n');console.log('Recorded original terminal controls',snapshot.length,'checkpoints')}
})().catch(e=>{console.error(e);process.exitCode=1});
