//! Pure news Markdown rendering. No Native startup, store or agent call.
use crate::{HandlerError, Reply, Request};
use http::StatusCode;
use linkify::{LinkFinder, LinkKind};
use pulldown_cmark::{Event, LinkType, Options, Parser, Tag, TagEnd, html};
mod uri;
use std::{
    borrow::Cow,
    collections::{HashMap, HashSet},
    sync::LazyLock,
};

pub const MAX_INPUT_BYTES: usize = 256 * 1024;
#[derive(Debug, Clone, Copy)]
pub enum Profile {
    News,
}
fn esc(s: &str) -> String {
    comandos_web_view::escape::text(s)
}
fn http_url(s: &str) -> bool {
    let s = s.trim().to_ascii_lowercase();
    s.starts_with("http://") || s.starts_with("https://")
}
fn host(url: &str) -> String {
    url::Url::parse(url)
        .ok()
        .and_then(|u| {
            u.host_str()
                .map(|s| s.trim_start_matches("www.").to_lowercase())
        })
        .unwrap_or_default()
}
fn anchor(url: &str, title: &str, generated_hrefs: &mut HashSet<String>) -> String {
    let url = normalized_href(url);
    let authority = url
        .split_once("://")
        .map(|(_, rest)| rest.split(['/', '?', '#']).next().unwrap_or(rest))
        .unwrap_or_default();
    let attribute = if !(authority.contains("xn--") || authority.contains('%'))
        || url::Url::parse(&url).is_ok()
    {
        "href"
    } else {
        generated_hrefs.insert(url.to_string());
        "data-news-href"
    };
    format!(
        "<a {}=\"{}\"{} target=\"_blank\" rel=\"noopener noreferrer nofollow\">",
        attribute,
        esc(&url),
        if title.is_empty() {
            String::new()
        } else {
            format!(" title=\"{}\"", esc(title))
        }
    )
}

fn normalized_href(href: &str) -> Cow<'_, str> {
    // Parser destinations have already decoded entities. Their PUA scalars
    // are Unicode data, never evidence of the UTF-16 transport codec.
    let href = idna_href(href);
    if href.is_ascii() {
        return href;
    }
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let extra = href.bytes().filter(|byte| !byte.is_ascii()).count() * 2;
    let mut encoded = String::with_capacity(href.len() + extra);
    for byte in href.bytes() {
        if byte.is_ascii() {
            encoded.push(char::from(byte));
        } else {
            encoded.push('%');
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 15)]));
        }
    }
    Cow::Owned(encoded)
}
// markdown-it normalizes an international hostname without rewriting the
// spelling of the scheme, port, userinfo or path.
fn idna_href(href: &str) -> Cow<'_, str> {
    uri::unicode_destination(href)
}

struct HtmlText {
    source: String,
    marker: String,
}
impl HtmlText {
    // This operation is restricted to raw source bytes, where the preparer's
    // absent, unbordered marker can only come from a masked HTML position.
    fn original(&self, range: std::ops::Range<usize>) -> String {
        let value = self.source.get(range).unwrap_or_default();
        if self.marker.is_empty() {
            value.into()
        } else {
            value.replace(&self.marker, "<")
        }
    }

    // Restore a Text token before coalescing. Borrowed tokens point into the
    // prepared source; entity-decoded tokens do not. Never sweep a decoded
    // string for markers: a legitimate entity may produce the same glyphs.
    fn text_token(&self, value: &str, range: std::ops::Range<usize>) -> String {
        let borrowed = (value.as_ptr() as usize)
            .checked_sub(self.source.as_ptr() as usize)
            .and_then(|start| start.checked_add(value.len()).map(|end| start..end))
            .filter(|span| self.source.get(span.clone()) == Some(value));
        if let Some(span) = borrowed {
            self.original(span)
        } else if self.source.get(range.clone()) == Some(value) {
            self.original(range)
        } else if let Some(raw) = self
            .source
            .get(range)
            .filter(|raw| raw.starts_with('&') && raw.ends_with(';'))
        {
            uri::entity_text(raw, value)
        } else {
            value.into()
        }
    }

    // Code tokens never decode entities. Their only transformations trim or
    // normalize whitespace; the punctuation marker is absent from raw input
    // and cannot be generated by those transformations. Require its actual
    // source position inside this code token before restoring it.
    fn code_token(&self, value: &str, range: std::ops::Range<usize>) -> String {
        if !self.marker.is_empty()
            && self
                .source
                .get(range)
                .is_some_and(|raw| raw.contains(&self.marker))
        {
            value.replace(&self.marker, "<")
        } else {
            value.into()
        }
    }

    // Map raw autolink boundaries back to prepared-source offsets. Restoring
    // each marker changes its UTF-8 byte width, so offsets cannot be reused.
    fn original_offsets(&self, range: std::ops::Range<usize>) -> (String, Vec<(usize, usize)>) {
        let mut raw = String::new();
        let mut offsets = Vec::new();
        let mut at = range.start;
        while at < range.end {
            offsets.push((raw.len(), at));
            let tail = self.source.get(at..range.end).unwrap_or_default();
            if !self.marker.is_empty() && tail.starts_with(&self.marker) {
                raw.push('<');
                at += self.marker.len();
            } else if let Some(ch) = tail.chars().next() {
                raw.push(ch);
                at += ch.len_utf8();
            } else {
                break;
            }
        }
        offsets.push((raw.len(), at));
        (raw, offsets)
    }
}

// pulldown has no html:false option. Mask raw HTML's opening punctuation before
// parsing so normal Markdown paragraphs, soft breaks and formatting still run.
// The mask is absent from the input, unbordered and entirely punctuation. Thus
// it cannot overlap raw literal input or alter emphasis flanking. Restore only
// source-origin tokens, before joining decoded entities. Code keeps its own
// non-decoding boundary; no marker reaches HTML or the JSON boundary.
fn html_as_text(text: &str, options: Options) -> HtmlText {
    let mut positions = HashSet::new();
    for (event, range) in Parser::new_ext(text, options).into_offset_iter() {
        if matches!(event, Event::Html(_) | Event::InlineHtml(_)) {
            for (offset, ch) in text.get(range.clone()).unwrap_or_default().char_indices() {
                if ch != '<' {
                    continue;
                }
                let at = range.start + offset;
                let tail = text.get(at + 1..).unwrap_or_default();
                let angle_http = tail
                    .find('>')
                    .and_then(|end| tail.get(..end))
                    .is_some_and(|url| http_url(url) && !url.chars().any(char::is_whitespace));
                if !angle_http {
                    positions.insert(at);
                }
            }
        }
    }
    if positions.is_empty() {
        return HtmlText {
            source: text.into(),
            marker: String::new(),
        };
    }
    const START: char = '⁅';
    const PUNCT: &[char] = &[
        '⁆', '⁇', '⁈', '⁉', '⁊', '⁋', '⁌', '⁍', '⁎', '⁏', '⁐', '⁑', '⁒', '⁓', '⁔', '⁕', '⁖', '⁗',
        '⁘', '⁙', '⁚', '⁛', '⁜', '⁝', '⁞',
    ];
    let marker = if !text.contains(START) {
        START.to_string()
    } else {
        // There are more candidates than input positions. Every candidate
        // starts with START and its remaining symbols cannot be START.
        let mut width = 5;
        let mut candidates = PUNCT.len().pow(4);
        while candidates <= text.len() {
            width += 1;
            candidates = candidates.saturating_mul(PUNCT.len());
        }
        let chars = text.chars().collect::<Vec<_>>();
        let used = chars
            .windows(width)
            .filter_map(|window| {
                if window.first() != Some(&START) {
                    return None;
                }
                window.iter().skip(1).try_fold(0usize, |n, ch| {
                    PUNCT
                        .iter()
                        .position(|p| p == ch)
                        .map(|p| n * PUNCT.len() + p)
                })
            })
            .collect::<HashSet<_>>();
        let mut number = (0..candidates)
            .find(|n| !used.contains(n))
            .unwrap_or_default();
        let mut suffix = Vec::new();
        for _ in 1..width {
            suffix.push(PUNCT.get(number % PUNCT.len()).copied().unwrap_or('⁆'));
            number /= PUNCT.len();
        }
        std::iter::once(START)
            .chain(suffix.into_iter().rev())
            .collect()
    };
    let mut source = String::with_capacity(text.len());
    for (at, ch) in text.char_indices() {
        if positions.contains(&at) {
            source.push_str(&marker);
        } else {
            source.push(ch);
        }
    }
    HtmlText { source, marker }
}
fn tail(text: &str, url: &str) -> String {
    static HOST_LABEL: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"(?i)^(?:https?://)?((?:[a-z0-9-]+\.)+[a-z]{2,})(?:[/:?#]\S*)?$")
            .expect("valid static news host-label pattern")
    });
    let label = HOST_LABEL
        .captures(text.trim())
        .and_then(|c| c.get(1))
        .map(|m| m.as_str().trim_start_matches("www.").to_lowercase());
    let host = host(url);
    if label.is_some_and(|l| l != host) {
        format!(" <span class=\"nr-host\">({})</span>", esc(&host))
    } else {
        String::new()
    }
}
fn numeric_entity_terminator(text: &str, start: usize, end: usize) -> bool {
    text.get(end..).is_some_and(|tail| tail.starts_with(';'))
        && text
            .get(start..end)
            .and_then(|url| url.rsplit_once("&#"))
            .is_some_and(|(_, digits)| {
                if let Some(hex) = digits.strip_prefix(['x', 'X']) {
                    !hex.is_empty() && hex.bytes().all(|ch| ch.is_ascii_hexdigit())
                } else {
                    !digits.is_empty() && digits.bytes().all(|ch| ch.is_ascii_digit())
                }
            })
}
// Markdown-it's raw URL matcher retains a semicolon only when followed by
// something other than whitespace, a control character or end of input.
fn numeric_entity_end(text: &str, start: usize, end: usize) -> usize {
    if numeric_entity_terminator(text, start, end)
        && text
            .get(end + 1..)
            .and_then(|tail| tail.chars().next())
            .is_some_and(|next| !next.is_whitespace() && !next.is_control())
    {
        end + 1
    } else {
        end
    }
}
// LinkFinder accepts Unicode spaces inside URL paths. The original matcher
// treats Unicode whitespace and C0/C1 controls as boundaries, but keeps FEFF
// and ZWSP in the URL. Split before matching so punctuation trimming applies
// at the real boundary and subsequent URLs are still visited. This streams
// borrowed segments without allocating a collection of matches.
fn autolinks<'a>(
    text: &'a str,
    finder: &'a LinkFinder,
) -> impl Iterator<Item = std::ops::Range<usize>> + 'a {
    let delimiter = |ch: char| ch.is_whitespace() || ch.is_control();
    text.split_inclusive(delimiter)
        .scan(0, move |at, segment| {
            let start = *at;
            *at += segment.len();
            Some((start, segment.trim_end_matches(delimiter)))
        })
        .flat_map(move |(start, segment)| {
            finder
                .links(segment)
                .map(move |link| start + link.start()..start + link.end())
        })
}
fn linkified(text: &str, generated_hrefs: &mut HashSet<String>) -> String {
    let mut finder = LinkFinder::new();
    finder.kinds(&[LinkKind::Url]).url_must_have_scheme(true);
    let mut out = String::new();
    let mut at = 0;
    for link in autolinks(text, &finder) {
        // fuzzyEmail=false: a domain within an e-mail is not a link either.
        if text.get(..link.start).is_some_and(|s| s.ends_with('@')) {
            continue;
        }
        let end = numeric_entity_end(text, link.start, link.end);
        let visible = text
            .get(link.start..end)
            .unwrap_or_default()
            .split(['«', '»', '“', '”', '‘', '’', '…'])
            .next()
            .unwrap_or_default();
        let mut href = if visible.contains("://") {
            visible.replace('\\', "%5C")
        } else {
            format!("http://{visible}")
        };
        // These are non-delimiters. Preserve the original href spelling while
        // leaving the displayed URL's Unicode text untouched.
        if href.contains('\u{feff}') {
            href = href.replace('\u{feff}', "%EF%BB%BF");
        }
        if href.contains('\u{200b}') {
            href = href.replace('\u{200b}', "%E2%80%8B");
        }
        if !http_url(&href) {
            continue;
        }
        out.push_str(&esc(text.get(at..link.start).unwrap_or_default()));
        // Bare destinations still originate in source, before entities.
        let href = uri::transport_destination(&href);
        out.push_str(&anchor(&href, "", generated_hrefs));
        out.push_str(&esc(visible));
        out.push_str("</a>");
        at = link.start + visible.len();
    }
    out.push_str(&esc(text.get(at..).unwrap_or_default()));
    out
}
// Markdown-it detects a bare URL before processing escapes and entities.
// Pulldown decodes these into separate Text spans. Recover bytes only for raw
// autolinks whose boundaries map to the decoded run; escapes and entities
// outside those links, explicit links and code keep their normal treatment.
fn restore_autolink_source(
    prepared: &HtmlText,
    spans: &[(std::ops::Range<usize>, String)],
    decoded: &str,
) -> String {
    let Some(first) = spans.first() else {
        return decoded.into();
    };
    let Some(last) = spans.last() else {
        return decoded.into();
    };
    let (raw, source_offsets) = prepared.original_offsets(first.0.start..last.0.end);
    let source_at = |offset| {
        source_offsets
            .binary_search_by_key(&offset, |(raw, _)| *raw)
            .ok()
            .and_then(|index| source_offsets.get(index).map(|(_, source)| *source))
    };
    let offset = |at: usize| {
        let mut decoded_at = 0;
        for (range, value) in spans {
            if at == range.start {
                return Some(decoded_at);
            }
            if at == range.end {
                return Some(decoded_at + value.len());
            }
            if range.contains(&at) && prepared.original(range.clone()) == *value {
                return Some(decoded_at + prepared.original(range.start..at).len());
            }
            decoded_at += value.len();
        }
        None
    };
    let mut finder = LinkFinder::new();
    finder.kinds(&[LinkKind::Url]).url_must_have_scheme(true);
    let mut out = String::new();
    let mut at = 0;
    for link in autolinks(&raw, &finder) {
        let matched = raw.get(link.clone()).unwrap_or_default();
        if !(matched.contains('\\') || matched.contains("&#")) || !http_url(matched) {
            continue;
        }
        if raw.get(..link.start).is_some_and(|s| s.ends_with('@')) {
            continue;
        }
        let mut end = numeric_entity_end(&raw, link.start, link.end);
        let (Some(source_start), Some(source_end)) = (source_at(link.start), source_at(end)) else {
            continue;
        };
        let mut end_decoded = offset(source_end);
        // A URL may end inside a source entity whose decoded Text token is
        // indivisible. Restore that whole token, including its punctuation,
        // while linkified independently applies the contextual URL boundary.
        // This recovers raw bytes; it does not add the semicolon to the href.
        if end_decoded.is_none()
            && numeric_entity_terminator(&raw, link.start, end)
            && let Some(decoded_end) = source_at(end + 1).and_then(offset)
        {
            end += 1;
            end_decoded = Some(decoded_end);
        }
        let (Some(start), Some(end_decoded)) = (offset(source_start), end_decoded) else {
            continue;
        };
        if start < at {
            continue;
        }
        let Some(prefix) = decoded.get(at..start) else {
            continue;
        };
        if decoded.get(start..end_decoded).is_none() {
            continue;
        }
        out.push_str(prefix);
        out.push_str(raw.get(link.start..end).unwrap_or_default());
        at = end_decoded;
    }
    out.push_str(decoded.get(at..).unwrap_or_default());
    out
}
/// Live createRenderer profile: raw HTML is text; no remote image elements.
pub fn render(text: &str, _profile: Profile) -> String {
    let options = Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH;
    // markdown-it replaces literal NUL before parsing, including code and URLs.
    // Keep the common path borrowed; normalize only inputs containing NUL.
    let text = if text.contains('\0') {
        Cow::Owned(text.replace('\0', "\u{fffd}"))
    } else {
        Cow::Borrowed(text)
    };
    let prepared = html_as_text(&text, options);
    let source = &prepared.source;
    let mut events = Vec::new();
    let mut links: Vec<(String, String)> = Vec::new();
    let mut generated_hrefs = HashSet::new();
    let mut code = 0usize;
    let mut skip = 0usize;
    let mut strikes = Vec::new();
    // A single tilde is literal in markdown-it. Convert these boundaries
    // before Text coalescing, so a URL's closing tilde remains part of the
    // same text run and receives the original autolink treatment.
    let base_parser = Parser::new_ext(source, options);
    let definitions = base_parser
        .reference_definitions()
        .iter()
        .map(|(id, definition)| (id.to_string(), definition.span.clone()))
        .collect::<HashMap<_, _>>();
    let parsed = base_parser
        .into_offset_iter()
        .map(|(event, mut range)| {
            let event = match event {
                Event::Start(Tag::Strikethrough) => {
                    let double = source
                        .get(range.start..)
                        .is_some_and(|s| s.starts_with("~~"));
                    strikes.push(double);
                    if double {
                        Event::Start(Tag::Strikethrough)
                    } else {
                        range.end = range.start + 1;
                        Event::Text("~".into())
                    }
                }
                Event::End(TagEnd::Strikethrough) => {
                    if strikes.pop().unwrap_or(false) {
                        Event::End(TagEnd::Strikethrough)
                    } else {
                        range.start = range.end.saturating_sub(1);
                        Event::Text("~".into())
                    }
                }
                event => event,
            };
            (event, range)
        })
        .collect::<Vec<_>>();
    let mut parser = parsed.into_iter().peekable();
    while let Some((event, range)) = parser.next() {
        if skip > 0 {
            match event {
                Event::Start(_) => skip += 1,
                Event::End(_) => skip -= 1,
                _ => {}
            }
            continue;
        }
        match event {
            Event::Start(Tag::CodeBlock(kind)) => {
                code += 1;
                events.push(Event::Start(Tag::CodeBlock(kind)));
            }
            Event::End(TagEnd::CodeBlock) => {
                code = code.saturating_sub(1);
                events.push(Event::End(TagEnd::CodeBlock));
            }
            Event::Start(Tag::Link {
                dest_url,
                title,
                link_type,
                id,
            })
            | Event::Start(Tag::Image {
                dest_url,
                title,
                link_type,
                id,
            }) => {
                let raw_source = match link_type {
                    LinkType::Inline | LinkType::Autolink | LinkType::Email => {
                        source.get(range.clone())
                    }
                    _ => definitions
                        .get(id.as_ref())
                        .and_then(|span| source.get(span.clone())),
                };
                let raw = if dest_url.contains('\u{e000}') || dest_url.contains('\u{fffd}') {
                    raw_source.and_then(|raw| match link_type {
                        LinkType::Inline => uri::inline_destination(raw),
                        LinkType::Autolink | LinkType::Email => {
                            raw.strip_prefix('<').and_then(|s| s.strip_suffix('>'))
                        }
                        _ => uri::reference_destination(raw),
                    })
                } else {
                    None
                };
                let dest_url = raw
                    .and_then(|raw| uri::parsed_destination(raw, link_type))
                    .map_or_else(|| Cow::Borrowed(dest_url.as_ref()), Cow::Owned);
                let title = if title.contains('\u{e000}') || title.contains('\u{fffd}') {
                    raw_source
                        .and_then(|raw| uri::source_title(raw, link_type))
                        .map_or_else(|| Cow::Borrowed(title.as_ref()), Cow::Owned)
                } else {
                    Cow::Borrowed(title.as_ref())
                };
                let image = source
                    .get(range.start..)
                    .is_some_and(|s| s.starts_with("!"));
                if http_url(&dest_url) {
                    if image {
                        events.push(Event::Text("!".into()));
                    }
                    events.push(Event::Html(
                        anchor(&dest_url, &title, &mut generated_hrefs).into(),
                    ));
                    links.push((dest_url.to_string(), String::new()));
                } else {
                    events.push(Event::Text(prepared.original(range).into()));
                    skip = 1;
                }
            }
            Event::End(TagEnd::Link) | Event::End(TagEnd::Image) => {
                if let Some((url, label)) = links.pop() {
                    events.push(Event::Html(format!("</a>{}", tail(&label, &url)).into()));
                }
            }
            Event::Text(t) => {
                // Literal punctuation and entities can split one visible URL
                // into adjacent Text events. Linkify the complete text run.
                let token = if code > 0 {
                    prepared.code_token(&t, range.clone())
                } else {
                    prepared.text_token(&t, range.clone())
                };
                let mut spans = vec![(range, token.clone())];
                let mut t = token;
                while matches!(parser.peek(), Some((Event::Text(_), _))) {
                    if let Some((Event::Text(next), next_range)) = parser.next() {
                        let next = if code > 0 {
                            prepared.code_token(&next, next_range.clone())
                        } else {
                            prepared.text_token(&next, next_range.clone())
                        };
                        t.push_str(&next);
                        spans.push((next_range, next));
                    }
                }
                let t = if code == 0 && links.is_empty() {
                    restore_autolink_source(&prepared, &spans, &t)
                } else {
                    t
                };
                if let Some((_, label)) = links.last_mut() {
                    label.push_str(&t);
                }
                if code > 0 || !links.is_empty() {
                    events.push(Event::Text(t.into()));
                } else {
                    let rendered = linkified(&t, &mut generated_hrefs);
                    events.push(Event::Html(rendered.into()));
                }
            }
            Event::Code(t) => {
                let t = prepared.code_token(&t, range);
                if let Some((_, label)) = links.last_mut() {
                    label.push_str(&t);
                }
                events.push(Event::Code(t.into()));
            }
            Event::Html(t) => {
                events.push(Event::Start(Tag::Paragraph));
                events.push(Event::Html(
                    linkified(
                        &prepared.text_token(t.trim_end_matches('\n'), range),
                        &mut generated_hrefs,
                    )
                    .into(),
                ));
                events.push(Event::End(TagEnd::Paragraph));
            }
            Event::InlineHtml(t) => events.push(Event::Html(
                linkified(&prepared.text_token(&t, range), &mut generated_hrefs).into(),
            )),
            Event::Start(Tag::Strikethrough) => events.push(Event::Html("<s>".into())),
            Event::End(TagEnd::Strikethrough) => events.push(Event::Html("</s>".into())),
            Event::Start(Tag::Table(_)) => {
                events.push(Event::Html("<div class=\"nr-table-wrap\"><table>".into()))
            }
            Event::End(TagEnd::Table) => events.push(Event::Html("</table></div>".into())),
            other => events.push(other),
        }
    }
    let mut raw = String::new();
    html::push_html(&mut raw, events.into_iter());
    let tags: HashSet<_> = [
        "p",
        "br",
        "strong",
        "em",
        "del",
        "s",
        "a",
        "ul",
        "ol",
        "li",
        "blockquote",
        "code",
        "pre",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hr",
        "table",
        "thead",
        "tbody",
        "tr",
        "th",
        "td",
        "div",
        "span",
    ]
    .into_iter()
    .collect();
    // The live DOMPurify URI policy removes numeric `start` values. Preserve
    // that visible list numbering; only target/rel are explicitly URI-safe.
    let attrs = ["href", "target", "rel", "class", "title"]
        .into_iter()
        .collect();
    let clean = ammonia::Builder::default()
        .tags(tags)
        // Only our generated anchors can supply this internal attribute: raw
        // HTML has already become text. Enforce the same HTTP(S) policy before
        // restoring its structural name after Ammonia's tree sanitization.
        .tag_attributes(
            [("a", ["data-news-href"].into_iter().collect())]
                .into_iter()
                .collect(),
        )
        .attribute_filter(move |element, attribute, value| {
            if attribute == "data-news-href"
                && (element != "a"
                    || !http_url(value)
                    || value.chars().any(char::is_control)
                    || !generated_hrefs.contains(value))
            {
                None
            } else {
                Some(Cow::Borrowed(value))
            }
        })
        .generic_attributes(attrs)
        .url_schemes(["http", "https"].into_iter().collect())
        .url_relative(ammonia::UrlRelative::Deny)
        .link_rel(None)
        .clean(&raw)
        .to_string();
    uri::restore_href_attributes(&clean).into_owned()
}
/// Scoped browser-string decoder; other POST domains retain their existing JSON policy.
pub fn parse_request(raw: &[u8]) -> Option<serde_json::Value> {
    let raw = std::str::from_utf8(raw).ok()?;
    serde_json::from_str(&comandos_web_view::utf16::json_to_unicode(raw)).ok()
}
pub fn handle(request: &Request) -> Result<Reply, HandlerError> {
    if request.body.len() > MAX_INPUT_BYTES {
        return Reply::json(
            StatusCode::PAYLOAD_TOO_LARGE,
            &serde_json::json!({"error":"texto demasiado largo"}),
        );
    }
    let Some(body) = request.data.as_ref() else {
        return Reply::json(
            StatusCode::BAD_REQUEST,
            &serde_json::json!({"error":"JSON invalido"}),
        );
    };
    if body.get("profile").and_then(serde_json::Value::as_str) != Some("news") {
        return Reply::json(
            StatusCode::BAD_REQUEST,
            &serde_json::json!({"error":"perfil desconocido"}),
        );
    }
    let Some(text) = body.get("text").and_then(serde_json::Value::as_str) else {
        return Reply::json(
            StatusCode::BAD_REQUEST,
            &serde_json::json!({"error":"text debe ser texto"}),
        );
    };
    let text_bytes = char::decode_utf16(comandos_web_view::utf16::decode(text))
        .map(|c| c.map(|c| c.len_utf8()).unwrap_or(3))
        .sum::<usize>();
    if text_bytes > MAX_INPUT_BYTES {
        return Reply::json(
            StatusCode::PAYLOAD_TOO_LARGE,
            &serde_json::json!({"error":"texto demasiado largo"}),
        );
    }
    let output = serde_json::json!({"html":render(text,Profile::News)}).to_string();
    Ok(Reply::bytes(
        StatusCode::OK,
        "application/json",
        comandos_web_view::utf16::json_to_javascript(&output).into_bytes(),
    ))
}
