const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {doc,makeEl}=require('./foundation_helpers_dom.cjs');
const elements=new Map(),intervals=[];const storage=new Map(),calls=[],toasts=[];
const el=(id,hidden=false)=>{let n=makeEl('div',{id,...(hidden?{class:'hidden'}:{})},doc.body);n.style.setProperty=(k,v)=>n.style[k]=v;n.getBoundingClientRect=()=>({top:10,bottom:30,height:20,right:200});n.offsetWidth=120;n.offsetHeight=100;n.select=()=>{};Object.defineProperty(n,'dataset',{get(){return this._data ||= Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]));}});elements.set(id,n);doc.body.appendChild(n);return n};
for(const id of ['notif-panel','pomo-panel','btn-notif','notif-badge','newsess','ns-cwd','ns-harness','ns-motor','ns-model','ns-effort','ns-acct','ns-motor-acct','ns-motor-wrap','ns-model-wrap','ns-effort-wrap','ns-acct-wrap','ns-motor-acct-wrap','ns-motor-acct-note','ns-go','ns-note','ns-danger','ns-cancel','ns-crumbs','ns-dirlist','ns-fs-state','ns-dir-create','ns-fs-up','ns-profile-wrap','ns-profile','mdl-menu','limits-strip','btn-sov','sovereignty','sov-body'])el(id,['newsess','mdl-menu','pomo-panel'].includes(id));
doc.getElementById=id=>elements.get(id)||doc.body.querySelector("#"+id)||null;doc.querySelector=s=>s.startsWith('#')?doc.getElementById(s.slice(1)):doc.body.querySelector(s);doc.querySelectorAll=s=>doc.body.querySelectorAll(s);doc.execCommand=()=>true;
Object.defineProperty(global,"navigator",{value:{},configurable:true,writable:true});
Object.assign(global,{window:global,document:doc,location:{hostname:'127.0.0.1',protocol:'http:',origin:'http://127.0.0.1:4777'},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v))},navigator:{clipboard:{writeText:async t=>{global.copied=t;}}},CSS:{escape:s=>s},L:'es',tf:es=>es,svg:()=>'<svg></svg>',ICON:{},S:{list:[],favs:new Set(),sel:'',selTs:0},__comandosState:()=>global.S,sidebarActiveTab:()=>global.active||{},rowKey:it=>it.session+(it.pane?'|'+it.pane:''),render:()=>{},toast:(m,b)=>toasts.push([m,b]),tick:()=>{global.ticks=(global.ticks||0)+1},ulog:()=>{},innerWidth:1000,innerHeight:800,activeView:'panel',ONLY_PANEL:false,setInterval:(fn,ms)=>{intervals.push({fn,ms});return intervals.length},clearInterval:()=>{}});
let handler=async(p,b)=>p==='/prefs'?{favorites:[]}:{newSince:{},queue:[]};global.api=(p,b)=>{calls.push([p,b]);return handler(p,b)};
const wasm=require(path.resolve(process.argv[2]));Date.now=()=>3761000;wasm.mount_helpers_fixture();
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
(async()=>{
 for(const c of JSON.parse(fs.readFileSync(path.join(__dirname,'foundation_helpers_golden.json')))){assert.equal(global[c.name](...c.args),c.expected,c.name+' '+JSON.stringify(c.args));}
 assert.equal(WEBTERM,false);assert.equal(TERM_PRIMARY_ATTEMPTS,3);assert.equal(TERM_PRIMARY_RETRY_MS,400);assert.equal(TERM_PRIMARY_PROBE_TIMEOUT_MS,800);
 const live=S;S.list=[{session:'s',pane:'%1',alive:true,operable:true},{session:'s',pane:'%2',alive:true,operable:true}];global.active={session:'s',pane:'%2',ts:3};S.sel='s|%1';S.selTs=4000;assert.equal(pickSel(S.list),S.list[0]);S.selTs=2000;assert.equal(pickSel(S.list),S.list[1]);assert.equal(S,live);
 indexUsage({projects:[{panes:[{tmux_session:'s',tmux_pane:'%1',model:'claude-opus'}]}]});assert.equal(usageForItem({session:'s'}),usageForItem(S.list[0]));
 let release;handler=(p,b)=>p==='/prefs-set'?new Promise(r=>release=r):Promise.resolve({favorites:[]});const write=setSessionFavorite('s',true);await settle();assert(S.favs.has('s'));assert(favoritePending.has('s'));const read=refreshFavorites();await read;assert(S.favs.has('s'));release({favorites:['s']});await write;assert(!favoritePending.has('s'));
 favoriteReadAt=0;let finishRead;handler=(p,b)=>p==='/prefs'?new Promise(r=>finishRead=r):Promise.resolve({favorites:['s','t']});const lateRead=refreshFavorites();await settle();await setSessionFavorite('t',true);finishRead({favorites:[]});await lateRead;assert(S.favs.has('t'));
 handler=async()=>{throw Error('fixture failure')};await assert.rejects(setSessionFavorite('s',false));assert(S.favs.has('s'));
 Object.assign(NS,{harness:'claude',motor:'claude'});PROVIDERS={harnesses:{claude:{accounts:[{alias:'named',selectable:true,motorSelectable:false,state:'ready'}]}},motors:{claude:{models:[{id:'one',efforts:['low'],defaultEffort:'low'}]}},matrix:[{harness:'claude',motor:'claude',id:'route',selectable:true,driver:'acp'}]};assert.equal(nsAccountItems('claude','motor')[0].disabled,false);PROVIDERS.matrix[0].driver='gateway';assert.equal(nsAccountItems('claude','motor')[0].disabled,true);Object.assign(NS,{profileId:'profile',model:'preserved',effort:'high',harnessAccount:'named'});nsSelectDefaults();nsEnsureAccount('claude','harnessAccount');assert.equal(NS.model,'preserved');assert.equal(NS.effort,'high');assert.equal(NS.harnessAccount,'named');delete NS.profileId;nsSelectDefaults();assert.equal(NS.model,'one');assert.equal(NS.effort,'low');nsRender();const chip=doc.getElementById('ns-harness').querySelector('[data-id="shell"]');assert.equal(chip.listenerCount('click'),1,'wizard chip handler');chip.dispatch('click',chip);assert.equal(NS.harness,'shell');assert(doc.getElementById('ns-model-wrap').classList.contains('hidden'));NS.harness='claude';NS.motor='claude';nsSelectDefaults();
 nfHydrate({});storage.set('cc-nf-dismiss','{"old":1}');nfHydrate({});assert.equal(nfDismissed('old'),false);MODEL_NEWS={newSince:{claude:{models:['model-a'],at:100}}};S.list=[];notifPaint();assert(doc.getElementById('notif-panel').querySelector('.nf2'));const before=calls.length;const b=doc.getElementById('notif-panel').querySelector('[data-act="dismiss"]');b.dispatch('click',b);assert.equal(nfDismissed('mn|claude|model-a'),true);await settle();assert(calls.slice(before).every(([p])=>p==='/prefs-set'));

 const fsPending=[];handler=(p)=>new Promise(resolve=>fsPending.push([p,resolve]));const first=nsBrowse('/home/test/old');const second=nsBrowse('/home/test/new');await settle();fsPending[1][1]({home:'/home/test',base:'/home/test',path:'/home/test/new',dirs:[{name:'NEW',path:'/home/test/new/NEW'}],exists:true});await second;fsPending[0][1]({home:'/home/test',base:'/home/test',path:'/home/test/old',dirs:[{name:'OLD',path:'/home/test/old/OLD'}],exists:true});await first;assert(doc.getElementById('ns-dirlist').textContent.includes('NEW'));assert(!doc.getElementById('ns-dirlist').textContent.includes('OLD'));assert.equal(nsShortHome('/home/test/new'),'~/new');
 handler=async()=>({newSince:{},queue:[]});await wasm.attach_helpers_fixture();await settle();assert(intervals.some(x=>x.ms===450));let poll=intervals.find(x=>x.ms===450).fn;S.list=[{session:'s',pane:'%1',alive:true,model:'old'}];MOTOR_PENDING.set('s|%1',{operationId:'new'});handler=async()=>({operationId:'old',state:'done',ok:true,model:'wrong'});poll();await settle();assert.equal(S.list[0].model,'old');assert(MOTOR_PENDING.has('s|%1'));handler=async()=>({operationId:'new',state:'done',ok:true,model:'correct',detail:'ok'});poll();await settle();assert.equal(S.list[0].model,'correct');assert(!MOTOR_PENDING.has('s|%1'));
 MODEL_NEWS={newSince:{claude:{models:['model-b','model-c'],at:100}}};storage.set('cc-nf-dismiss','{}');const panel=doc.getElementById('notif-panel');panel.classList.remove('hidden');notifPaint();nfToggleDetail(panel,'mn|claude|model-b,model-c');assert.equal(panel.querySelectorAll('.nf2-detail').length,1);assert.equal(panel.querySelectorAll('[data-url]').length,2);nfToggleDetail(panel,'mn|claude|model-b,model-c');assert.equal(panel.querySelectorAll('.nf2-detail').length,0);const target=makeEl('button',{},null);doc.dispatch('click',{target,composedPath:()=>[target,panel,doc.body]});assert(!panel.classList.contains('hidden'));doc.dispatch('click',{target,composedPath:()=>[target,doc.body]});assert(panel.classList.contains('hidden'));
 Date.now=()=>15000000;nfSave('cc-nf-pins',[{key:'oldpin',title:'saved link',savedAt:1,reminded:false}]);nfSave('cc-nf-snooze',{'oldnotice':1});nfSave('cc-nf-snooze-meta',{'oldnotice':{title:'snoozed',notified:false}});handler=async()=>({});intervals.find(x=>x.ms===120000).fn();await settle();assert.equal(nfPins()[0].reminded,true);assert.equal(nfStore('cc-nf-snooze-meta').oldnotice.notified,true);assert.equal(calls.filter(([p])=>p==='/notify-popup').length,2); // saved pin and snooze both expire
 handler=async()=>({stores:[{label:'secret',path:'/tmp/private',kind:'secret',private:true,bytes:1024,tables:[{name:'a',rows:5}]}],outbound:[{on:false,label:'remote',how:'disabled'}],browser:[{key:'fixture',label:'browser state'}]});await sovRender();assert(doc.getElementById('sov-body').textContent.includes('0600 ✓'));assert(doc.getElementById('sov-body').textContent.includes('APAGADO'));
 console.log('Actual helpers WASM: 38 original outputs + live state, selection, usage, favorite race/rollback, account/profile, synchronous notifications, operation guard, detached event path passed');
})().catch(e=>{console.error(e);process.exitCode=1});
