// Runs the actual integrated WASM library against the compiled page body, offline.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const wasmPath=path.resolve(process.argv[2]||'');
const scenarios=['early','late','topological','unknown','attach','startup','ack','gradual','models-empty','models-null','models-false'];
if(!process.argv[3]){for(const scenario of scenarios){const r=cp.spawnSync(process.execPath,[__filename,wasmPath,scenario],{encoding:'utf8'});process.stdout.write(r.stdout);process.stderr.write(r.stderr);assert.equal(r.status,0,scenario);}console.log('Full native boot: 11 actual WASM DOM/startup/failure scenarios passed');process.exit(0);}
const scenario=process.argv[3],{doc,makeEl,parse}=require('./full_native_boot_dom.cjs');
const registry=fs.readFileSync(path.resolve(__dirname,'../src/registry.rs'),'utf8');
const inventory=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../../xtask/web/inventory.json')));const ids=inventory.pages['index.html'].map(id=>inventory.units.find(u=>u.id===id).component);assert.equal(ids.length,48);if(scenario==='topological'){const ordered=[],seen=new Set();function visit(id){if(seen.has(id))return;seen.add(id);const metadata=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../components/'+id+'.json')));for(const dep of metadata.deps||[])if(ids.includes(dep))visit(dep);ordered.push(id);}for(const id of ids)visit(id);ids.splice(0,ids.length,...ordered);}for(const id of ids)assert(registry.includes('id: \"'+id+'\",'),'registered '+id);
const root=makeEl('html',{},null),head=makeEl('head',{},root);root.appendChild(head);
head.appendChild(makeEl('meta',{name:'comandos-web',content:scenario==='gradual'?'':ids.join(' ')+(scenario==='unknown'?' missing-component':'')},head));
if(scenario!=='gradual')head.appendChild(makeEl('meta',{name:'comandos-web-mode',content:'native'},head));
doc.documentElement=root;doc.head=head;doc.readyState=scenario==='early'||scenario==='gradual'?'loading':'interactive';doc.body=null;
function installBody(){doc.body=makeEl('body',{},root);root.appendChild(doc.body);parse(fs.readFileSync(path.resolve(__dirname,'../../comandos-web-view/src/index_page_body.html'),'utf8'),doc.body);const form=doc.body.querySelector('#srv-form');for(const k of['host','hostname','user','port','identity','orig','remember'])form[k]=form.querySelector('[name="'+k+'"]');form.reset=()=>{};}
if(scenario!=='early'&&scenario!=='gradual')installBody();
doc.querySelector=s=>root.querySelector(s);doc.querySelectorAll=s=>root.querySelectorAll(s);doc.getElementById=id=>root.querySelector('#'+id);doc.cookie='';doc.hidden=false;doc.visibilityState='visible';
const calls=[],timers=[],listeners={},storage=new Map(),errors=[];let finishConf,finishAck;
process.on('unhandledRejection',e=>errors.push(String(e)));
Object.defineProperty(global,'navigator',{configurable:true,writable:true,value:{}});
Object.assign(global,{window:global,document:doc,location:{protocol:'https:',hostname:'dash.private.invalid',origin:'https://dash.private.invalid',href:'https://dash.private.invalid/?web=native',search:'?web=native',reload(){throw Error('unexpected reload')}},navigator:{platform:'Linux',maxTouchPoints:0,language:'en',onLine:true,sendBeacon:()=>true},innerWidth:1100,innerHeight:800,devicePixelRatio:1,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},sessionStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:false,addEventListener(){},removeEventListener(){}}),getComputedStyle:()=>({getPropertyValue:()=>'',fontSize:'14px'}),addEventListener:(t,f)=>(listeners[t]||=[]).push(f),removeEventListener(){},dispatchEvent(){},setTimeout:(f,ms)=>{timers.push([f,ms]);return timers.length},clearTimeout(){},setInterval:(f,ms)=>{timers.push([f,ms]);return timers.length},clearInterval(){},requestAnimationFrame:f=>{timers.push([f,0]);return timers.length},cancelAnimationFrame(){},ResizeObserver:class{observe(){}disconnect(){}},MutationObserver:class{observe(){}disconnect(){}},Notification:class{static permission='denied'},CustomEvent:class{constructor(type,options){this.type=type;Object.assign(this,options)}},Event:class{constructor(type,options){this.type=type;Object.assign(this,options)}},Element:class{static[Symbol.hasInstance](o){return o?.nodeType===1}},Window:class{static[Symbol.hasInstance](o){return o===global}},HTMLElement:class{static[Symbol.hasInstance](o){return o?.nodeType===1}},HTMLInputElement:class{static[Symbol.hasInstance](o){return o?.tagName==='INPUT'}}});
const oldCreate=doc.createElement;doc.createElement=tag=>{const n=oldCreate(tag);if(tag==='canvas')n.getContext=()=>({measureText:s=>({width:s.length*7}),fillRect(){},clearRect(){},fillText(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},scale(){},setTransform(){}});return n;};
const routes={ '/conf':{_lang:'en',VOLUME:'50',SPEAK_DONE:'0',SPEAK_ATTENTION:'0'},'/prefs':{favorites:[],theme:'dia',button_style:'sutil',tabs_layout:'row'},'/remote-state':{remoteOn:false,terminalState:'off',urls:{},qrAvailable:false},'/ssh':[], '/tabs':[], '/state':[], '/tab-history':[], '/usage/state':{},'/chains':{chains:[]},'/commands/catalog':{catalog:{commands:[],groups:[]},cliInPane:'codex'},'/workspace':{revision:1,groups:[],tabs:[]}};
if(scenario.startsWith('models-')) routes['/models/latest']={ 'models-empty':{}, 'models-null':null, 'models-false':{newSince:false}}[scenario];
function response(payload,ok=true){return{ok,status:ok?200:400,statusText:ok?'OK':'Bad Request',json:async()=>structuredClone(payload),text:async()=>JSON.stringify(payload)}}
global.fetch=async(input,options={})=>{const url=typeof input==='string'?input:input.url;const p=new URL(url,location.origin).pathname;calls.push({path:p,options});if(p==='/conf'&&!finishConf){for(const name of['api','tf','initApp','mountCommandSidebar','mountChainPage','loadRemote','loadPrefs','loadSsh','loadConf','arm','tick','rowKey','render','quickTerminalInstance','selectPaneInFrame'])assert.equal(typeof global[name],'function','global mounted before startup: '+name);assert(global.openTerms instanceof Map);assert(global.S);if(scenario==='startup'){return new Promise(r=>finishConf=()=>r(response(routes[p])));}}if(p==='/web/ready'){if(scenario==='ack')return response({},false);if(scenario==='early')return new Promise(r=>finishAck=()=>r(response({})));return response({});}if(p.startsWith('/workspace/client'))return response({activeTabId:null});if(p==='/presence')return response({});if(!(p in routes))throw Error('unexpected offline route '+p);return response(routes[p]);};
const wasm=require(wasmPath);if(scenario==='attach')doc.getElementById('poll').remove();
const settle=async()=>{for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));};
(async()=>{
 wasm.boot('native-private-fixture');
 if(scenario==='early'){assert.equal(global.S,undefined);assert.equal(calls.length,0);assert.equal(__comandosBootState,'waiting-dom');wasm.boot('ignored');assert.equal(doc.listenerCount('DOMContentLoaded'),1);installBody();doc.readyState='interactive';doc.dispatch('DOMContentLoaded');}
 if(scenario==='gradual'){assert.equal(__comandosReady,true);assert.equal(calls.filter(c=>c.path==='/web/ready').length,1);console.log('PASS gradual head compatibility');return;}
 await settle();
 if(scenario==='startup'){assert.equal(typeof finishConf,'function');doc.getElementById('tab-prev').remove();finishConf();await settle();}
 if(scenario==='early'){assert.equal(typeof finishAck,'function',JSON.stringify(global.__comandosBootReport));assert.notEqual(global.__comandosReady,true);assert.equal(__comandosBootState,'reporting');finishAck();await settle();}
 if(['unknown','attach','startup','ack'].includes(scenario)){assert.equal(__comandosBootState,'failed',JSON.stringify(__comandosBootReport));assert.notEqual(global.__comandosReady,true);assert.notEqual(global.__comandosAttached,true);assert(__comandosBootReport.failed.length);assert.equal(calls.filter(c=>c.path==='/web/ready').length,scenario==='ack'?1:0);if(scenario==='unknown')assert.equal(calls.length,0);if(scenario==='attach')assert.equal(calls.some(c=>c.path==='/conf'),false);assert.deepEqual(errors,[]);assert.equal(__comandosBootReport.failed[0].id,{unknown:'missing-component',attach:'ui-general',startup:'ui-general',ack:'@ready'}[scenario]);console.log('PASS native blocks '+scenario,JSON.stringify(__comandosBootReport.failed));return;}
 assert.equal(__comandosBootState,'ready',JSON.stringify(__comandosBootReport));assert.equal(__comandosReady,true);assert.equal(__comandosAttached,true);assert.deepEqual(__comandosBootReport.failed,[]);assert.deepEqual([...__comandosBootReport.mounted].sort(),[...ids].sort());assert(global.__comandosStartup instanceof Promise);assert.equal(doc.getElementById('poll').listenerCount('input'),2);assert.equal(typeof doc.getElementById('tab-prev').onclick,'function');assert.equal(typeof global.NewsReader,'object');await __comandosStartup;for(const p of['/conf','/remote-state','/prefs','/ssh','/state','/commands/catalog','/chains'])assert(calls.some(c=>c.path===p),'startup route '+p);const ready=calls.filter(c=>c.path==='/web/ready');assert.equal(ready.length,1);assert.deepEqual([...JSON.parse(ready[0].options.body).mounted].sort(),[...ids].sort());const before=[calls.length,timers.length,doc.listenerCount('click')];wasm.boot('ignored');await settle();assert.deepEqual([calls.length,timers.length,doc.listenerCount('click')],before);assert.deepEqual(errors,[]);console.log('PASS native '+scenario+': 48 mounts, complete startup, ACK and idempotency');
})().catch(e=>{console.error(e);process.exitCode=1});
