const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {doc,makeEl}=require('./servers_dom.cjs');const elements=new Map(),calls=[],bridge=[],opens=[],toasts=[],timers=[],animations=[],snapshot=[];let native=false,reduced=false,resizes=0,finishQuick;
function el(id,hidden=false){const n=makeEl('div',{id,...hidden?{class:'hidden'}:{}},null);n.style.setProperty=(k,v)=>n.style[k]=v;n.getBoundingClientRect=()=>({height:20,bottom:40,left:980});n.offsetWidth=180;n.reset=()=>{};elements.set(id,n);doc.body.appendChild(n);return n;}
for(const k of['srv-form','srv-form-title','srv-cancel','ssh-bar','ssh-toggle','ssh-chips','ssh-count','srv-list','servers','settings','remote','usage','ssh-manage','btn-terminal','btn-newsess','btn-notif','tab-term','tab-left','tab-new','tab-rows','btn-menu','btn-servers','menu-panel','servers-panel','view-panel','splitter'])el(k,['menu-panel','servers-panel'].includes(k));
const form=elements.get('srv-form');for(const k of['host','hostname','user','port','identity','orig','remember'])form[k]=makeEl('input',{},null);form.reset=()=>{for(const k of['host','hostname','user','port','identity','orig'])form[k].value='';form.remember.checked=false;};
doc.getElementById=k=>elements.get(k)||doc.body.querySelector('#'+k);doc.querySelector=s=>doc.getElementById(s.slice(1));doc.querySelectorAll=s=>doc.body.querySelectorAll(s);doc.body.classList.add('app');
let hosts=[{host:'<safe>',hostname:'example.org',user:'dev',port:22}];let handler=async(p,b)=>p==='/ssh'?hosts:{session:'ssh-s',label:'label',connected:true};
Object.assign(global,{window:global,document:doc,$:s=>doc.querySelector(s),tf:es=>es,t:s=>s,api:async(p,b)=>{calls.push([p,b]);return handler(p,b)},inApp:()=>native,openInApp:(...a)=>opens.push(['app',...a]),openTerm:(...a)=>opens.push(['web',...a]),WEBTERM:false,NS:{intoPane:{session:'old'}},activeView:'terms',showView:v=>{global.activeView=v},nsOpen:()=>{opens.push(['wizard']);return Promise.resolve()},quickTerminalInstance:()=>({open:()=>new Promise(r=>finishQuick=r)}),applyTabsLayout:v=>doc.body.classList.toggle('tabs-rows',v==='rows'),toast:(m,b=false)=>toasts.push([m,b]),webkit:{messageHandlers:{centro:{postMessage:s=>bridge.push(JSON.parse(s))}}},localStorage:{values:new Map(),getItem(k){return this.values.get(k)||null},setItem(k,v){this.values.set(k,String(v))}},matchMedia:()=>({matches:reduced}),innerWidth:1000,dispatchEvent:()=>resizes++,setTimeout:(fn,ms)=>{timers.push([fn,ms]);return timers.length}});
for(const k of['view-panel','splitter'])elements.get(k).animate=(frames,options)=>{const animation={frames,options,finish(){this.onfinish?.()},cancel(){this.oncancel?.()}};animations.push(animation);return animation;};
const original=process.argv[2]==='--record';if(original){const src=fs.readFileSync(path.resolve(__dirname,'../../../dash/index.html'),'utf8');const a=src.indexOf('// ---------- servidores ----------'),b=src.indexOf('// ---------- notificaciones del sistema ----------',a);vm.runInThisContext(src.slice(a,b),{filename:'original-servers-fixture'});}else{const wasm=require(path.resolve(process.argv[2]));wasm.mount_servers_fixture();wasm.attach_servers_fixture();}
const settle=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};
function save(name,data){snapshot.push({name,data});}
(async()=>{
 await loadSsh();save('hosts',{count:elements.get('ssh-count').textContent,chips:elements.get('ssh-chips').children.filter(n=>n.nodeType===1).map(n=>[n.textContent,n.title]),rows:elements.get('srv-list').querySelectorAll('.srv-row').map(n=>[n.querySelector('.srv-name').textContent,n.querySelector('.srv-tgt').textContent])});
 elements.get('srv-list').querySelector('.ed').click();save('edit',{host:form.host.value,orig:form.orig.value,remember:form.remember.checked,title:elements.get('srv-form-title').textContent,cancelHidden:elements.get('srv-cancel').classList.contains('hidden')});elements.get('srv-cancel').click();save('cancel',{host:form.host.value,orig:form.orig.value,remember:form.remember.checked});
 fillSrvForm({host:'old',hostname:'before'});form.host.value=' renamed ';form.hostname.value=' new ';form.user.value=' user ';form.port.value=' 2222 ';form.identity.value=' key ';form.dispatch('submit',form);await settle();save('update',{request:calls.find(([p])=>p==='/ssh-update'),resetHost:form.host.value});
 form.host.value='new';form.hostname.value='newhost';form.dispatch('submit',form);await settle();save('add-remember',{request:calls.find(([p])=>p==='/ssh-add'),setup:calls.find(([p,b])=>p==='/ssh-key-setup'&&b.host==='new')});
 let del=elements.get('srv-list').querySelector('.del');let before=calls.filter(([p])=>p==='/ssh-del').length;del.click();save('delete-arm',{armed:del.classList.contains('arm'),text:del.textContent,deleteCalls:calls.filter(([p])=>p==='/ssh-del').length-before});del.click();await settle();save('delete-confirm',calls.find(([p])=>p==='/ssh-del'));del=elements.get('srv-list').querySelector('.del');del.click();timers.at(-1)[0]();save('delete-expiry',{armed:del.classList.contains('arm'),text:del.textContent,ms:timers.at(-1)[1]});
 native=true;await connectHost('native');native=false;WEBTERM=true;await openSshTab('web');await setupSshKey('web');WEBTERM=false;await connectHost('focus');save('ssh-routing',{opens:opens.slice(),focus:calls.filter(([p])=>p==='/focus')});
 elements.get('btn-newsess').click();save('new-session',{activeView,intoPane:NS.intoPane,open:opens.at(-1)});native=true;const beforeOpen=opens.length;elements.get('btn-newsess').click();elements.get('btn-terminal').click();elements.get('btn-notif').click();elements.get('tab-left').click();save('native-capture',{bridge:bridge.slice(),bubbleCalls:opens.length-beforeOpen});native=false;
 elements.get('btn-terminal').click();save('terminal-busy',{disabled:elements.get('btn-terminal').disabled,busy:elements.get('btn-terminal').getAttribute('aria-busy')});finishQuick();await settle();save('terminal-complete',{disabled:elements.get('btn-terminal').disabled,busy:elements.get('btn-terminal').getAttribute('aria-busy')});
 handler=async(p)=>{if(p==='/prefs-set')throw Error('rows failed');return hosts};elements.get('tab-rows').click();await settle();save('rows-rollback',{rows:doc.body.classList.contains('tabs-rows'),toast:toasts.at(-1)});
 const panelBtn=elements.get('tab-left');panelBtn.click();let hide=animations.at(-2);save('hide-start',{hidden:doc.body.classList.contains('panel-hidden'),duration:hide.options.duration});hide.cancel();hide.finish();save('hide-end',{hidden:doc.body.classList.contains('panel-hidden'),resizes,fx:elements.get('view-panel')._fx});panelBtn.click();let show=animations.at(-2);save('show-start',{hidden:doc.body.classList.contains('panel-hidden'),duration:show.options.duration});show.finish();reduced=true;panelBtn.click();save('reduced',{hidden:doc.body.classList.contains('panel-hidden'),animations:animations.length});
 const menu=elements.get('menu-panel'),button=elements.get('btn-menu');button.click();save('menu-position',{hidden:menu.classList.contains('hidden'),expanded:button.getAttribute('aria-expanded'),top:menu.style.top,left:menu.style.left});const detached=makeEl('button',{},null);doc.dispatch('click',{target:detached,composedPath:()=>[detached,menu,doc.body]});save('detached-path',menu.classList.contains('hidden'));doc.dispatch('keydown',{key:'Escape'});save('menu-escape',{hidden:menu.classList.contains('hidden'),focused:doc.activeElement.id});button.click();doc.dispatch('click',{target:detached,composedPath:()=>[detached,doc.body]});save('menu-outside',menu.classList.contains('hidden'));elements.get('btn-servers').click();await settle();save('servers-open',{hidden:elements.get('servers-panel').classList.contains('hidden'),bar:elements.get('ssh-bar').classList.contains('open'),expanded:elements.get('ssh-toggle').getAttribute('aria-expanded')});
 const out=path.join(__dirname,'servers_golden.json');if(original){fs.writeFileSync(out,JSON.stringify(snapshot,null,2)+'\n');console.log('Recorded original servers',snapshot.length,'checkpoints');}else{assert.deepEqual(snapshot,JSON.parse(fs.readFileSync(out)));console.log('Actual servers WASM equals original across',snapshot.length,'SSH/header/animation/popover checkpoints');}
})().catch(e=>{console.error(e);process.exitCode=1});
