[package]
name = "comandos-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "comandos_cli"
path = "src/lib.rs"

[[bin]]
name = "comandos"
path = "src/main.rs"

[dependencies]
comandos-extensions = { path = "../comandos-extensions" }
comandos-runtime = { path = "../comandos-runtime" }
comandos-server = { path = "../comandos-server" }
sha2.workspace = true

[lints]
workspace = true
